server:
  port: 9010
###dubbo 注册服务名称
dubbo:
  application:
    name: order
  ###dubbo服务地址
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
  consumer:
    timeout: 5000