server:
  port: 9000
dubbo:
  application:
    name: member
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.liuwq.member.service.impl